### ISSUE TITLE
Can't run - Incompatible with the version of Windows you are running

### ISSUE THREAD

**Issue by jeffstokes72** [randomascii/blogstuff#5]
C:\data>FindZombieHandles.exe
This version of C:\data\FindZombieHandles.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

Microsoft Windows [Version 10.0.17133.1]
x64

Any suggestions? Running as admin, not sure what the deal is..

**Comment by jeffstokes72** [comment]
![image](https://user-images.githubusercontent.com/9102841/38712515-3f842d06-3e9a-11e8-81db-41b3a4f2d88a.png)

**Comment by randomascii** [comment]
That seems like a bad clone. The message is clearly stating that the binary is a 16-bit application and it is not. 16-bit applications don't run on 64-bit Windows at all and 64-bit Windows has been the default for developers for about a decade, so FindZombieHandles.exe is definitely not a 16-bit application.

How are you getting the tool? It doesn't look like you have cloned the repo, so ???

Try cloning the repo. Be sure to run the tool from the repo directory because it needs other files as well.

**Comment by jeffstokes72** [comment]
Sorry was out of town. I'll clone the repo (just did) and try that.  I had
just right clicked the exe in your repo and said save as.

**Comment by jeffstokes72** [comment]
So, I cloned, and did a .zip download, and it works. Before I was right clicking each file and doing a save link as. Which isn't smart, I know. So this is on me, my bad :D

**Comment by theCrius** [comment]
Hey, bringing this up again as downloading the repo as a zip cause the browser to flag it as "unsafe" and downloading the files one by one cause the error message reported above.

**Comment by randomascii** [comment]
I'd recommend cloning it. I don't know how to stop browsers from flagging it.

**Comment by jeffstokes72** [comment]
Hey Bruce, I noticed Defender flagged the download I have of the repro,
claimed malware was in it. Guessing a misdeteciton.

**Comment by jeffstokes72** [comment]
to be clear this was about a month ago, and no longer happens with defender

**Comment by theCrius** [comment]
Quick workaround, using JDownloader2 can work around the issue. Can confirm that cloning the entire repo solve the issue reported initially. Cheers
