### ISSUE TITLE
FindZombieHandles - Can't enable debug privilege even when running on admin

### ISSUE THREAD

**Issue by instilledbee** [randomascii/blogstuff#6]
Hi,

I tried to clone the repo and run the prebuilt binaries for FindZombieHandles. The program works as expected although it warns that it can't find all the zombies due to being unable to get debug privileges. However, even when running as admin I still get the same warning:

![image](https://user-images.githubusercontent.com/5665389/38839926-7bbe649e-420f-11e8-88ec-56be8943593d.png)

I'm on Windows 10 Pro 1709, if that matters.

Thanks!

**Comment by randomascii** [comment]
Odd. I just tried the same thing, from powershell, and it works fine for me. My best guess would be that the admin check is buggy or else your admin accounts are configured to restrict this power. You could try debugging the code. Or, look for process that appear to be holding a lot of handles. That could be tough because 2385 isn't really enough to be easily findable. Maybe look at suspects in procexp with the lower pane showing handles to see if you can find anything that way. Sorry!

**Comment by instilledbee** [comment]
Thanks for the response. It helped point me to a solution where I had to enable the "Debug Programs" policy for my user account via the Local Security Policy settings. After updating that setting and restarting my PC, the app works properly now.😃 

![image](https://user-images.githubusercontent.com/5665389/38871297-073d8cac-4283-11e8-86e5-e11abb534458.png)
